//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessangerServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
